import requests
import pymysql
from datetime import datetime

# ==========================================
# 1. CONFIGURATION - ADD YOUR TOKENS HERE
# ==========================================
TELEGRAM_BOT_TOKEN = 'YOUR_BOT_TOKEN_HERE'
BOSS_CHAT_ID = 'YOUR_BOSS_CHAT_ID_HERE'

DB_CONFIG = {
    'host': '127.0.0.1',
    'user': 'root',
    'password': '',
    'db': 'sale_dash_db',
    'cursorclass': pymysql.cursors.DictCursor
}

def send_telegram_msg(text):
    """Sends a message to the specified Telegram chat."""
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {"chat_id": BOSS_CHAT_ID, "text": text, "parse_mode": "HTML"}
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        print("Telegram report sent successfully!")
    except Exception as e:
        print(f"Failed to send Telegram message: {e}")

def generate_daily_report():
    """Generates the daily performance summary for the boss."""
    
    # Create multiple date formats to match how your team might type it
    today_ymd = datetime.now().strftime('%Y-%m-%d') # e.g., 2026-04-13
    today_d_b = datetime.now().strftime('%d-%b')    # e.g., 13-Apr
    today_d_b_y = datetime.now().strftime('%d-%b-%Y') # e.g., 13-Apr-2026
    
    connection = None
    try:
        connection = pymysql.connect(**DB_CONFIG)
        with connection.cursor() as cursor:
            # 1. Total Revenue Today
            cursor.execute("""
                SELECT SUM(Total) as total_rev 
                FROM financial_sales_ledger 
                WHERE DateStr LIKE %s OR DateStr LIKE %s OR DateStr LIKE %s
            """, (f"%{today_ymd}%", f"%{today_d_b}%", f"%{today_d_b_y}%"))
            rev_result = cursor.fetchone()
            total_revenue = rev_result['total_rev'] or 0

            # 2. Top Seller Today
            cursor.execute("""
                SELECT Sale_Rep, SUM(Total) as total_sales
                FROM financial_sales_ledger
                WHERE DateStr LIKE %s OR DateStr LIKE %s OR DateStr LIKE %s
                GROUP BY Sale_Rep
                ORDER BY total_sales DESC
                LIMIT 1
            """, (f"%{today_ymd}%", f"%{today_d_b}%", f"%{today_d_b_y}%"))
            top_seller_result = cursor.fetchone()
            top_seller = top_seller_result['Sale_Rep'] if top_seller_result else "No sales today"
            top_seller_amount = top_seller_result['total_sales'] if top_seller_result else 0

            # 3. Total Meetings/Leads Today
            cursor.execute("""
                SELECT COUNT(*) as total_meetings 
                FROM client_contacts_leads 
                WHERE Contacted_Date LIKE %s OR Contacted_Date LIKE %s OR Contacted_Date LIKE %s
            """, (f"%{today_ymd}%", f"%{today_d_b}%", f"%{today_d_b_y}%"))
            meetings_result = cursor.fetchone()
            total_meetings = meetings_result['total_meetings'] or 0

        # Construct the Message
        report_msg = (
            f"📊 <b>STB Daily Sales Report</b>\n"
            f"📅 Date: {datetime.now().strftime('%d %B %Y')}\n\n"
            f"💰 <b>Total Revenue Today:</b> ${float(total_revenue):,.2f}\n"
            f"🤝 <b>New Leads/Meetings:</b> {total_meetings}\n\n"
            f"🏆 <b>Top Seller of the Day:</b>\n"
            f"👤 {top_seller} (${float(top_seller_amount):,.2f})\n\n"
            f"<i>Report auto-generated by STB System</i> 🚀"
        )
        
        send_telegram_msg(report_msg)

    except Exception as e:
        print(f"Database error: {e}")
    finally:
        if connection and connection.open:
            connection.close()

if __name__ == "__main__":
    print("Generating Daily Report...")
    generate_daily_report()